namespace Samagra.AiEval;

internal static class EvalDocuments
{
    public static readonly (string Source, string Content)[] All =
    [
        ("return-policy",
         "Samagra Return Policy. Customers may return most products within 30 days of delivery. The product must be unused, in its original packaging, with all tags attached. Refunds are processed within 5 to 7 working days after we receive and inspect the returned item, and are credited to the original payment method. Shipping charges are non-refundable unless the product arrived damaged or we sent the wrong item. To start a return, go to My Orders, select the order, and click Request Return. Electronics and appliances have a shorter return window of 15 days from delivery. Items marked as final sale, personal care products, and innerwear cannot be returned for hygiene reasons. If a product arrives damaged, report it within 48 hours with photographs. Exchange is available only for size issues in clothing and must be requested within 15 days. For orders above 5000 rupees a reverse pickup is arranged free of charge. For smaller orders a pickup fee of 99 rupees is deducted from the refund amount."),

        ("shipping-policy",
         "Samagra Shipping Policy. Standard delivery takes 3 to 5 business days for metro cities and 5 to 8 business days for other locations. Express delivery costs an additional 149 rupees and delivers within 24 to 48 hours in select cities. Free shipping applies to all orders above 999 rupees. Orders placed before 2 PM are dispatched the same day. We currently deliver to over 19000 pin codes across India. International shipping is not available at this time. You can track your order from the My Orders section using the tracking ID sent by SMS and email. If delivery is attempted three times without success, the order is returned to our warehouse and refunded automatically. Cash on delivery is available for orders under 20000 rupees with a handling fee of 49 rupees. Bulky items such as furniture and large appliances may take 7 to 12 business days and require someone present at the delivery address."),

        ("warranty-policy",
         "Samagra Warranty Policy. All electronics carry a manufacturer warranty of 12 months from the date of delivery unless stated otherwise on the product page. Large appliances such as refrigerators and washing machines carry a 24 month warranty on the product and 60 months on the compressor or motor. Warranty covers manufacturing defects only. It does not cover physical damage, water damage, unauthorised repairs, or normal wear and tear. To raise a warranty claim, go to My Orders, select the product, and click Raise Warranty Claim, then upload the invoice and photographs of the issue. Claims are reviewed within 3 business days. Approved claims are handled by the manufacturer's service centre, not by Samagra directly. Extended warranty of an additional 12 months can be purchased at checkout for 8 percent of the product value. Warranty is not transferable if the product is resold."),

        ("payment-policy",
         "Samagra Payment Policy. We accept UPI, credit cards, debit cards, net banking, and cash on delivery. EMI is available on credit cards from major banks for orders above 3000 rupees, with tenures of 3, 6, 9, and 12 months. No cost EMI is offered on selected products for 3 and 6 month tenures. A failed payment is auto reversed by the bank within 5 to 7 working days. If money was deducted but the order was not created, raise a ticket with the transaction reference number and we will investigate within 48 hours. We do not store card details. Wallet balance from returns can be used for future purchases and does not expire. Gift cards are valid for 12 months from the date of issue and cannot be redeemed for cash. GST invoices are available for download from My Orders within 24 hours of delivery."),

        ("account-policy",
         "Samagra Account and Privacy Policy. Creating an account requires a valid email address and mobile number. Each mobile number can be linked to only one account. You can update your delivery address, phone number, and communication preferences from My Profile. Deleting your account is permanent and removes your order history, wallet balance, and saved addresses after 30 days. We use your data to process orders, provide support, and send delivery updates. We do not sell personal data to third parties. Marketing emails can be turned off from Notification Settings. Passwords must be at least 8 characters with one number and one special character. If you notice unauthorised activity, change your password and contact support immediately. We retain order records for 7 years as required by tax regulations even after account deletion.")
    ];
}