name: Samagra CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # ─────────────────────────────────────────
  # JOB 1 — .NET Backend Build & Test
  # ─────────────────────────────────────────
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Show Structure
      run: find . -name "*.sln"

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: BackEnd

    - name: Build
      run: dotnet build --no-restore
      working-directory: BackEnd

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: BackEnd

  # ─────────────────────────────────────────
  # JOB 2 — React Frontend Build
  # ─────────────────────────────────────────
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'

    - name: Install dependencies
      run: npm ci
      working-directory: FrontEnd/Samagra-app

    - name: Build React App
      run: npm run build
      working-directory: FrontEnd/Samagra-app
